config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resource :assertion, only: [:create, :destroy]
  post "/assertions/consume" => "assertions#create", as: :consume
  post "/assertions/logout" => "assertions#destroy", as: :logout
  resource :metadata, only: [:show]
  resources :service_providers, only: [:show, :new, :create, :destroy]
  resources :identity_providers, only: [:show, :new, :create, :update, :destroy]
  resources :providers, only: [:index]
  root to: "providers#index"
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  def index
    @identity_providers = Metadatum.identity_providers.limit(10)
    @service_providers = Metadatum.service_providers.limit(10)
  end
end

app/views/providers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Identity Providers</h1>
      <%= link_to "register", new_identity_provider_path %>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Entity Id</th>
            <th>Login</th>
            <th>Logout</th>
          </tr>
        </thead>
        <tbody>
          <% @identity_providers.each do |metadata| %>
            <tr>
              <td>
                <%= form_with url: identity_provider_path(metadata), method: :patch do |form| %>
                  <%= form.submit "Refresh" %>
                <% end %>

                <%= form_with url: identity_provider_path(metadata), method: :delete do |form| %>
                  <%= form.submit "Delete" %>
                <% end %>
              </td>
              <td>
                <%= link_to metadata.entity_id, identity_provider_path(metadata) %>
                <ul>
                  <% current_user(metadata.entity_id).attributes.each do |attribute| %>
                    <li title="<%= attribute[1] %>"> <%= attribute[0] %> <%= attribute[1].try(:truncate, 32) %> </li>
                  <% end if current_user?(metadata.entity_id) %>
                </ul>
              </td>
              <td>
                <% metadata.to_saml.single_sign_on_services.each do |service| %>
                  <%= form_with url: session_path, data: { remote: false } do |form| %>
                    <%= form.hidden_field :entity_id, value: metadata.entity_id %>
                    <%= form.hidden_field :binding, value: Saml::Kit::Bindings.to_symbol(service.binding) %>
                    <%= form.select :issuer, @service_providers.map { |x| [x.entity_id, x.entity_id] }, include_blank: true %>
                    <%= form.submit Saml::Kit::Bindings.to_symbol(service.binding).to_s.upcase %>
                  <% end %>
                <% end %>
              </td>
              <td>
                <% if current_user?(metadata.entity_id) %>
                  <% metadata.to_saml.single_logout_services.each do |service| %>
                    <%= form_with url: session_path, method: :delete, data: { remote: false } do |form| %>
                      <%= form.hidden_field :entity_id, value: metadata.entity_id %>
                      <%= form.hidden_field :binding, value: Saml::Kit::Bindings.to_symbol(service.binding) %>
                      <%= form.submit Saml::Kit::Bindings.to_symbol(service.binding).to_s.upcase %>
                    <% end %>
                  <% end %>
                <% else %>
                  <% metadata.to_saml.single_logout_services.each do |service| %>
                    <p><%= Saml::Kit::Bindings.to_symbol(service.binding).to_s.upcase %></p>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>


      <h1>Service Providers</h1>
      <%= link_to "new", new_service_provider_path %>

      <table class="table">
        <thead>
          <th></th>
          <th>Entity Id</th>
          <th>Signing Certificates</th>
          <th>Encryption Certificates</th>
        </thead>
        <tbody>
        <% @service_providers.each do |service_provider| %>
          <tr>
            <td>
              <%= button_to "delete", service_provider_path(service_provider), method: :delete %>
              <%= button_to "download", service_provider.entity_id, method: :get %>
            </td>
            <td><%= link_to service_provider.entity_id, service_provider.entity_id + "?view=true" %></td>
            <td><%= service_provider.certificates.signing.count %></td>
            <td><%= service_provider.certificates.encryption.count %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>