config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resource :assertion, only: [:create, :destroy]
  post "/assertions/consume" => "assertions#create", as: :consume
  post "/assertions/logout" => "assertions#destroy", as: :logout
  resource :metadata, only: [:show]
  resources :service_providers, only: [:show, :new, :create, :destroy]
  resources :identity_providers, only: [:show, :new, :create, :update, :destroy]
  resources :providers, only: [:index]
  root to: "providers#index"
end

app/controllers/assertions_controller.rb
class AssertionsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create, :destroy]

  def create
    saml_binding = sp.assertion_consumer_service_for(binding: :http_post)
    @saml_response = saml_binding.deserialize(params, configuration: current_configuration)
    logger.debug(@saml_response.to_xml(pretty: true))
    return render :error, status: :forbidden if @saml_response.invalid?

    session[@saml_response.issuer] = { id: @saml_response.name_id }.merge(@saml_response.attributes)
  end

  def destroy
    if params['SAMLRequest'].present?
      # IDP initiated logout
    elsif params['SAMLResponse'].present?
      saml_binding = sp.single_logout_service_for(binding: :http_post)
      @saml_response = saml_binding.deserialize(params, configuration: current_configuration)
      raise ActiveRecord::RecordInvalid.new(@saml_response) if @saml_response.invalid?
      session[@saml_response.issuer] = nil
    end
  end

  private

  def sp
    default_sp = Sp.default(request)
    if default_sp.entity_id == relay_state[:issuer]
      default_sp
    else
      Metadatum.find_by(entity_id: relay_state[:issuer]).to_saml
    end
  end

  def relay_state
    if params[:RelayState].present?
      JSON.parse(CGI.unescape(params[:RelayState])).with_indifferent_access
    else
      {}
    end
  end

  def current_configuration
    if sp == Sp.default(request)
      Saml::Kit.configuration
    else
      Metadatum.find_by(entity_id: relay_state[:issuer]).configuration
    end
  end
end

app/views/assertions/create.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Received Response</h1>
      <%= render partial: "spinner" %>
      <%= debug @saml_response.to_xhtml %>
    </div>
  </div>
</div>

<%= javascript_tag do %>
  window.onload = function(){
    window.setTimeout(function(){
      window.location.href = '<%= providers_path %>';
    }, 5000);
  };
<% end %>

app/views/assertions/destroy.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Received Response</h1>
      <%= render partial: "spinner" %>
      <%= debug @saml_response.to_xhtml %>
    </div>
  </div>
</div>

<%= javascript_tag do %>
  window.onload = function(){
    window.setTimeout(function(){
      window.location.href = '<%= providers_path %>';
    }, 5000);
  };
<% end %>

app/views/assertions/error.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Error</h1>
      <ul>
        <% @saml_response.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>

      <%= debug @saml_response.try(:to_xml, pretty: true) %>
    </div>
  </div>
</div>